#!/bin/sh

echo "-- mount /dev"
/bin/mount -t devtmpfs none /dev

echo "initrd: alive"

echo "-- mkdir /mnt"
mkdir /mnt
echo "-- mount /mnt"
mount -t iso9660 -o ro /dev/sr0 /mnt

echo "-- mount /mnt/proc"
/bin/mount -t proc proc /mnt/proc

echo "-- mount /mnt/sys"
/bin/mount -t sysfs none /mnt/sys

echo "-- mount /mnt/dev"
/bin/mount -t devtmpfs none /mnt/dev

echo "-- running switch_root"
exec /bin/switch_root -c /dev/tty1 /mnt /bin/sinit