#!/bin/sh
echo "initrd: alive"

echo "-- mount /dev"
mount -t devtmpfs none /dev
echo "-- mount /proc"
mount -t devtmpfs none /proc

for arg in "$(cat /proc/cmdline)"; do
	case "$arg" in
		root=*)
			root="${arg#root=}"
			;;
		rootfstype=*)
			rootfstype="${arg#rootfstype=}"
			;;
		init=*)
			init="${arg#init=}"
			;;
	esac
done

echo "-- mount /mnt"
mount -t ${rootfstype:-iso9660} -o ro ${root:-/dev/sr0} /mnt

echo "-- mount /mnt/proc"
mount -t proc proc /mnt/proc
echo "-- mount /mnt/sys"
mount -t sysfs none /mnt/sys
echo "-- mount /mnt/dev"
mount -t devtmpfs none /mnt/dev

echo "-- running switch_root"
exec switch_root /mnt ${init:-/bin/sinit}